### ISSUE TITLE
`bench update` fails with the error

### ISSUE THREAD

**Issue by jitendraharpalani** [DigiThinkIT/frappe#244]
Running bench update is giving following traceback: 
```
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/jitendraharpalani/Jeet/workspace/bloomstack/apps/frappe/frappe/utils/bench_helper.py", line 97, in <module>
    main()
  File "/Users/jitendraharpalani/Jeet/workspace/bloomstack/apps/frappe/frappe/utils/bench_helper.py", line 18, in main
    click.Group(commands=commands)(prog_name='bench')
  File "/Users/jitendraharpalani/Jeet/workspace/bloomstack/env/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/Users/jitendraharpalani/Jeet/workspace/bloomstack/env/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/Users/jitendraharpalani/Jeet/workspace/bloomstack/env/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/jitendraharpalani/Jeet/workspace/bloomstack/env/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/jitendraharpalani/Jeet/workspace/bloomstack/env/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/jitendraharpalani/Jeet/workspace/bloomstack/env/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/Users/jitendraharpalani/Jeet/workspace/bloomstack/env/lib/python3.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/jitendraharpalani/Jeet/workspace/bloomstack/apps/frappe/frappe/commands/__init__.py", line 25, in _func
    ret = f(frappe._dict(ctx.obj), *args, **kwargs)
  File "/Users/jitendraharpalani/Jeet/workspace/bloomstack/apps/frappe/frappe/commands/site.py", line 235, in migrate
    migrate(context.verbose, rebuild_website=rebuild_website, skip_failing=skip_failing)
  File "/Users/jitendraharpalani/Jeet/workspace/bloomstack/apps/frappe/frappe/migrate.py", line 54, in migrate
    sync_jobs()
  File "/Users/jitendraharpalani/Jeet/workspace/bloomstack/apps/frappe/frappe/core/doctype/scheduled_job_type/scheduled_job_type.py", line 120, in sync_jobs
    insert_events(all_events, scheduler_events)
  File "/Users/jitendraharpalani/Jeet/workspace/bloomstack/apps/frappe/frappe/core/doctype/scheduled_job_type/scheduled_job_type.py", line 130, in insert_events
    insert_event_list(events, event_type, all_events)
  File "/Users/jitendraharpalani/Jeet/workspace/bloomstack/apps/frappe/frappe/core/doctype/scheduled_job_type/scheduled_job_type.py", line 142, in insert_event_list
    insert_single_event(frequency, event)
  File "/Users/jitendraharpalani/Jeet/workspace/bloomstack/apps/frappe/frappe/core/doctype/scheduled_job_type/scheduled_job_type.py", line 150, in insert_single_event
    frequency = frequency
  File "/Users/jitendraharpalani/Jeet/workspace/bloomstack/apps/frappe/frappe/model/document.py", line 248, in insert
    raise e
  File "/Users/jitendraharpalani/Jeet/workspace/bloomstack/apps/frappe/frappe/model/document.py", line 245, in insert
    self.db_insert()
  File "/Users/jitendraharpalani/Jeet/workspace/bloomstack/apps/frappe/frappe/model/base_document.py", line 336, in db_insert
    raise frappe.DuplicateEntryError(self.doctype, self.name, e)
frappe.exceptions.DuplicateEntryError: ('Scheduled Job Type', 'contract.update_status_for_contracts', IntegrityError(1062, "Duplicate entry 'contract.update_status_for_contracts' for key 'PRIMARY'"))
```

**Comment by Alchez** [comment]
**Solution:**

Ensure that all the following apps are on the specified branches:

- Frappe: `staging`
- ERPNext: `staging`
- Bloomstack Core: `staging`
